# Module 5: Assignment - Framework Installation and Setup 

In [1]:
%pip install torch


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [5]:
import torch

# Create a PyTorch tensor
x = torch.rand(5, 3)

# Print the tensor
print(x)


tensor([[0.9991, 0.3524, 0.0084],
        [0.1641, 0.9551, 0.4151],
        [0.3011, 0.8906, 0.3604],
        [0.6193, 0.8773, 0.2749],
        [0.0253, 0.8536, 0.3438]])


In [3]:
%pip install tensorflow

Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.9.0
    Uninstalling typing_extensions-4.9.0:
      Successfully uninstalled typing_extensions-4.9.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch 2.2.0 requires typing-extensions>=4.8.0, but you have typing-extensions 4.5.0 which is incompatible.

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [4]:
import tensorflow as tf

# Create a TensorFlow tensor
hello_tensor = tf.constant('Hello, TensorFlow!')

# Start a TensorFlow session and run the tensor
tf.print(hello_tensor)


2024-02-20 02:15:26.640124: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-02-20 02:15:26.666532: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


Hello, TensorFlow!


2024-02-20 02:15:29.070145: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-02-20 02:15:29.094887: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-02-20 02:15:29.095005: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

In [6]:
import tensorflow as tf

# Create a constant tensor
tensor = tf.constant([[1, 2], [3, 4]])

# Perform some operations
tensor_add = tensor + 2  # Add 2 to all elements
tensor_mul = tensor * 3  # Multiply all elements by 3

# Use TensorFlow's functionality to compute more complex operations
tensor_squared = tf.square(tensor)  # Square all elements

# Print the results
print("Original tensor:\n", tensor.numpy())
print("Tensor after addition:\n", tensor_add.numpy())
print("Tensor after multiplication:\n", tensor_mul.numpy())
print("Tensor squared:\n", tensor_squared.numpy())


Original tensor:
 [[1 2]
 [3 4]]
Tensor after addition:
 [[3 4]
 [5 6]]
Tensor after multiplication:
 [[ 3  6]
 [ 9 12]]
Tensor squared:
 [[ 1  4]
 [ 9 16]]


In [8]:
import torch

# Create a tensor
tensor = torch.tensor([[1, 2], [3, 4]], dtype=torch.int)

# Perform operations
tensor_add = tensor + 2  # Add 2 to all elements
tensor_mul = tensor * 3  # Multiply all elements by 3

# More complex operations
tensor_squared = tensor.square()  # Square all elements

# Print the results
print("Original tensor:\n", tensor)
print("Tensor after addition:\n", tensor_add)
print("Tensor after multiplication:\n", tensor_mul)
print("Tensor squared:\n", tensor_squared)


Original tensor:
 tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
Tensor after addition:
 tensor([[3, 4],
        [5, 6]], dtype=torch.int32)
Tensor after multiplication:
 tensor([[ 3,  6],
        [ 9, 12]], dtype=torch.int32)
Tensor squared:
 tensor([[ 1,  4],
        [ 9, 16]], dtype=torch.int32)
